"""
Storage Service - Handles file operations and result persistence
Manages HTML output files, metadata, and session history
"""

import os
import json
import aiofiles
from datetime import datetime
from typing import Dict, Any, List
from pathlib import Path


class StorageService:
    """Service for managing benchmark result storage"""
    
    def __init__(self, base_output_dir: str = "../outputs"):
        self.base_output_dir = Path(base_output_dir)
        self.base_output_dir.mkdir(exist_ok=True)
    
    def _get_session_directory(self, session_id: str, timestamp: datetime = None) -> Path:
        """Get or create directory for a benchmark session"""
        if timestamp is None:
            timestamp = datetime.now()
        
        # Format: benchmark_YYYYMMDD_HHMMSS_sessionid[:8]
        dir_name = f"benchmark_{timestamp.strftime('%Y%m%d_%H%M%S')}_{session_id[:8]}"
        session_dir = self.base_output_dir / dir_name
        session_dir.mkdir(exist_ok=True)
        
        return session_dir
    
    async def save_session_results(self, session_data: Dict[str, Any]) -> str:
        """
        Save complete session results including HTML files and metadata
        
        Args:
            session_data: Complete session data with results
            
        Returns:
            Path to the session directory
        """
        session_id = session_data["session_id"]
        session_start = datetime.fromisoformat(session_data["start_time"])
        session_dir = self._get_session_directory(session_id, session_start)
        
        # Save individual HTML files
        results = session_data["results"]
        
        # Handle different result structures based on mode
        if isinstance(results, dict):
            # Check if this is a chain mode result (has nested phases)
            if "responder_phase" in results and "materializer_phase" in results:
                # Chain mode - save files from both phases
                for phase_name, phase_results in results.items():
                    if phase_name in ["responder_phase", "materializer_phase"] and isinstance(phase_results, dict):
                        for model_id, result in phase_results.items():
                            if isinstance(result, dict) and result.get("status") == "success" and result.get("html_content"):
                                file_suffix = "_content" if phase_name == "responder_phase" else "_template"
                                await self._save_html_file(
                                    session_dir, 
                                    f"{model_id}{file_suffix}", 
                                    result["html_content"],
                                    result
                                )
            else:
                # Single phase mode
                for model_id, result in results.items():
                    if isinstance(result, dict) and result.get("status") == "success" and result.get("html_content"):
                        await self._save_html_file(
                            session_dir, 
                            model_id, 
                            result["html_content"],
                            result
                        )
        
        # Save metadata JSON
        await self._save_metadata(session_dir, session_data)
        
        # Save session summary
        await self._save_session_summary(session_dir, session_data)
        
        return str(session_dir)
    
    async def _save_html_file(
        self, 
        session_dir: Path, 
        model_id: str, 
        html_content: str,
        result_data: Dict[str, Any]
    ):
        """Save HTML output for a specific model"""
        filename = f"{model_id}.html"
        file_path = session_dir / filename
        
        # Add metadata comment to HTML
        metadata_comment = f"""
<!-- 
Generated by: {result_data.get('model_name', model_id)}
Duration: {result_data.get('duration_seconds', 0):.3f} seconds
Tokens: {result_data.get('total_tokens', 'N/A')}
Cost: ${result_data.get('cost_usd', 0):.6f}
Timestamp: {result_data.get('end_time', '')}
-->
"""
        
        # Insert metadata comment after <!DOCTYPE html> or at the beginning
        if html_content.strip().startswith('<!DOCTYPE'):
            # Find the end of DOCTYPE declaration
            doctype_end = html_content.find('>', html_content.find('<!DOCTYPE'))
            if doctype_end != -1:
                html_with_metadata = (
                    html_content[:doctype_end + 1] + 
                    metadata_comment + 
                    html_content[doctype_end + 1:]
                )
            else:
                html_with_metadata = metadata_comment + html_content
        else:
            html_with_metadata = metadata_comment + html_content
        
        async with aiofiles.open(file_path, 'w', encoding='utf-8') as f:
            await f.write(html_with_metadata)
    
    async def _save_metadata(self, session_dir: Path, session_data: Dict[str, Any]):
        """Save detailed metadata JSON file"""
        metadata_file = session_dir / "metadata.json"
        
        # Clean up session data for JSON serialization
        clean_session_data = session_data.copy()
        
        async with aiofiles.open(metadata_file, 'w', encoding='utf-8') as f:
            await f.write(json.dumps(clean_session_data, indent=2, ensure_ascii=False))
    
    async def _save_session_summary(self, session_dir: Path, session_data: Dict[str, Any]):
        """Save human-readable summary file"""
        summary_file = session_dir / "summary.txt"
        
        summary_lines = [
            "AI Model Benchmarking Results",
            "=" * 50,
            f"Session ID: {session_data['session_id']}",
            f"Prompt: {session_data.get('prompt', session_data.get('user_input', 'N/A'))[:100]}{'...' if len(session_data.get('prompt', session_data.get('user_input', ''))) > 100 else ''}",
            f"Start Time: {session_data['start_time']}",
            f"Duration: {session_data.get('duration_seconds', 0):.3f} seconds",
            "",
            "Results by Model:",
            "-" * 30
        ]
        
        # Handle different result structures
        results = session_data["results"]
        
        if isinstance(results, dict) and "responder_phase" in results and "materializer_phase" in results:
            # Chain mode - show both phases
            summary_lines.extend([
                "Chain Mode Results:",
                "-" * 20,
                ""
            ])
            
            # Show responder phase
            summary_lines.append("📝 Content Generation (Responder):")
            responder_results = results.get("responder_phase", {})
            for model_id, result in responder_results.items():
                if isinstance(result, dict):
                    status_icon = "✅" if result.get("status") == "success" else "❌"
                    duration = result.get("duration_seconds", 0)
                    cost = result.get("cost_usd", 0)
                    summary_lines.extend([
                        f"  {status_icon} {result.get('model_name', model_id)}",
                        f"     Duration: {duration:.3f}s | Cost: ${cost:.6f} | Tokens: {result.get('total_tokens', 'N/A')}",
                        ""
                    ])
            
            # Show materializer phase  
            summary_lines.append("🎨 Layout Generation (Materializer):")
            materializer_results = results.get("materializer_phase", {})
            for model_id, result in materializer_results.items():
                if isinstance(result, dict):
                    status_icon = "✅" if result.get("status") == "success" else "❌"
                    duration = result.get("duration_seconds", 0)
                    cost = result.get("cost_usd", 0)
                    summary_lines.extend([
                        f"  {status_icon} {result.get('model_name', model_id)}",
                        f"     Duration: {duration:.3f}s | Cost: ${cost:.6f} | Tokens: {result.get('total_tokens', 'N/A')}",
                        ""
                    ])
                    
            # Show timing analysis if available
            if "timing_analysis" in results:
                summary_lines.extend([
                    "⏱️ Timing Analysis:",
                    f"   Total models compared: {len(results['timing_analysis'].get('models_compared', []))}",
                    ""
                ])
        else:
            # Single phase mode
            sorted_results = sorted(
                results.items(),
                key=lambda x: x[1].get("duration_seconds", float('inf')) if isinstance(x[1], dict) else float('inf')
            )
            
            for model_id, result in sorted_results:
                if isinstance(result, dict):
                    status_icon = "✅" if result.get("status") == "success" else "❌"
                    duration = result.get("duration_seconds", 0)
                    cost = result.get("cost_usd", 0)
                    
                    summary_lines.extend([
                        f"{status_icon} {result.get('model_name', model_id)}",
                        f"   Duration: {duration:.3f}s",
                        f"   Cost: ${cost:.6f}",
                        f"   Status: {result.get('status', 'unknown')}",
                        f"   Tokens: {result.get('total_tokens', 'N/A')}",
                        ""
                    ])
        
        # Add summary statistics
        summary = session_data.get("summary", {})
        summary_lines.extend([
            "Summary Statistics:",
            "-" * 20,
            f"Total Models: {summary.get('total_models', 0)}",
            f"Successful: {summary.get('completed', 0)}",
            f"Failed: {summary.get('failed', 0)}",
            f"Total Cost: ${summary.get('total_cost', 0):.6f}",
            ""
        ])
        
        if summary.get("fastest_model"):
            fastest = summary["fastest_model"]
            summary_lines.extend([
                f"Fastest: {fastest['model_name']} ({fastest['duration_seconds']:.3f}s)",
            ])
        
        if summary.get("slowest_model"):
            slowest = summary["slowest_model"]
            summary_lines.extend([
                f"Slowest: {slowest['model_name']} ({slowest['duration_seconds']:.3f}s)",
            ])
        
        async with aiofiles.open(summary_file, 'w', encoding='utf-8') as f:
            await f.write('\n'.join(summary_lines))
    
    async def load_session_results(self, session_path: str) -> Dict[str, Any]:
        """Load session results from storage"""
        session_dir = Path(session_path)
        metadata_file = session_dir / "metadata.json"
        
        if not metadata_file.exists():
            raise FileNotFoundError(f"Metadata file not found: {metadata_file}")
        
        async with aiofiles.open(metadata_file, 'r', encoding='utf-8') as f:
            content = await f.read()
            return json.loads(content)
    
    async def list_sessions(self, limit: int = 20) -> List[Dict[str, Any]]:
        """List recent benchmark sessions"""
        sessions = []
        
        # Get all benchmark directories
        benchmark_dirs = [
            d for d in self.base_output_dir.iterdir() 
            if d.is_dir() and d.name.startswith("benchmark_")
        ]
        
        # Sort by creation time (newest first)
        benchmark_dirs.sort(key=lambda x: x.stat().st_mtime, reverse=True)
        
        for session_dir in benchmark_dirs[:limit]:
            metadata_file = session_dir / "metadata.json"
            
            if metadata_file.exists():
                try:
                    async with aiofiles.open(metadata_file, 'r', encoding='utf-8') as f:
                        content = await f.read()
                        session_data = json.loads(content)
                        
                        sessions.append({
                            "session_id": session_data["session_id"],
                            "prompt": session_data["prompt"][:100] + ("..." if len(session_data["prompt"]) > 100 else ""),
                            "start_time": session_data["start_time"],
                            "duration_seconds": session_data.get("duration_seconds"),
                            "total_models": session_data.get("summary", {}).get("total_models", 0),
                            "successful_models": session_data.get("summary", {}).get("completed", 0),
                            "total_cost": session_data.get("summary", {}).get("total_cost", 0),
                            "directory": str(session_dir)
                        })
                except Exception as e:
                    print(f"Error loading session {session_dir}: {e}")
        
        return sessions
    
    def get_html_file_path(self, session_path: str, model_id: str) -> str:
        """Get path to HTML file for a specific model in a session"""
        session_dir = Path(session_path)
        html_file = session_dir / f"{model_id}.html"
        return str(html_file) if html_file.exists() else None
